framework:
    notifier:
        chatter_transports:
#            main: '%env(SLACK_DSN)% || %env(TELEGRAM_DSN)%'
#            slack: '%env(SLACK_DSN)%'
#            telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
#            main: '%env(TWILIO_DSN)% || %env(AMAZON_SNS_DSN)%'
#            twilio: '%env(TWILIO_DSN)%'
#            sns: '%env(AMAZON_SNS_DSN)%'
        channel_policy:
#            urgent: ['sms/main', 'chat/main', 'email']
#            high: ['chat/main', 'email']
            urgent: [ 'email' ]
            high: [ 'email' ]
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
